# Generated by Django 3.1.4 on 2025-02-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20250206_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='phoned',
            new_name='contacted',
        ),
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
    ]
